site_name: RL Helicopter Game
site_author: Dan Dixey

theme: 'material'

# Repository
repo_url: 'https://github.com/dandxy89/rf_helicopter'

# Copyright
copyright: 'Copyright (c) 2016 Dan Dixey'

site_description: 'Documentation for the Helicopter modelling - using DQN and Q-Learning.'

dev_addr: '0.0.0.0:8189'

pages:
- Overview: index.md
- Project:
  - Detailed Overview: project_detail.md
  - Implementation: implementation.md
  - Q-Learning Models: q-learning.md
  - Release Notes: release_notes.md
  - Video Demo: videos.md
  - References: references.md

extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

markdown_extensions:
  - admonition
  - toc:
      permalink: '#'